#  A sample sky catalog config for galaxies only
catalog_name : toy5
area_partition :
  { type: healpix, ordering : ring, nside : 32}
root_directory : /global/cscratch1/sd/jrbogart/desc/skycatalogs/toy5_rowgroup
SED_models :
  -
    tophat :
       units : angstrom
       bin_parameters : [start, width]
       bins : [ [17402, 2596], [15143, 2259], [13177, 1966], [11467, 1710],
               [9978, 1489], [9395, 583], [8846, 549], [8329, 517],
               [7843, 486], [7385, 458], [6954, 431], [6548, 406],
               [6166, 382], [5806, 360], [5467, 3339], [5148, 319],
               [4848, 300], [4565, 283], [4299, 266], [4048, 251],
               [3812, 236], [ 3590, 222], [3381, 209], [3184, 197],
               [2998, 186], [2407, 591], [1933, 474], [1552, 381],
               [1246, 306], [1000, 246] ]

MW_extinction :
  r_v :
    mode : constant
    value : 3.1
  a_v :
    mode : lsst_band

object_types :
  galaxy :
      file_template : 'galaxy_(?P<healpix>\d+).parquet'
      data_file_type : parquet
      composite :
        bulge : required
        disk  : required
        knots : optional
  bulge_basic :
      subtype : bulge
      parent : galaxy
      sed_model : tophat
      internal_extinction : CCM
      MW_extinction : CCM
      spatial_model : sersic2D
  disk_basic :
      subtype : disk
      parent : galaxy
      sed_model : tophat
      internal_extinction : CCM
      MW_extinction : CCM
      spatial_model :  sersic2D
  knots_basic :
      subtype : knots
      parent : galaxy
      sed_model : tophat
      internal_extinction : CCM
      MW_extinction : CCM
      spatial_model :  knots
